
# Use different management port as security rule
management:
    port: 8081
    security.enabled: false

# Enable shutdown
endpoints.shutdown.enabled: true

# Eureka server
eureka:
  instance:
    appname: my-sample-thrift-server
    nonSecurePort: 3000
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/