
# Use different management port as security rule
management:
    port: 8081
    security.enabled: false

# Enable shutdown
endpoints.shutdown.enabled: true

# Thrift server config
mySampleThriftServer:
  port: 3000
  name: my-sample-thrift-server

# Eureka server
eureka:
  instance:
    appname: ${mySampleThriftServer.name}
    nonSecurePort: ${mySampleThriftServer.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client.serviceUrl.defaultZone: http://localhost:8761/eureka/

# DB
mySample.datasource:
  # For more see http://tomcat.apache.org/tomcat-7.0-doc/jdbc-pool.html#Common_Attributes
  username: root
  password: sbmvt123
  testOnBorrow: true
  validationQuery: SELECT 1
  url: jdbc:mysql://sbmvt-mysql-test:3306/my_sample

# Profiles
spring:
  profiles.active: test
---
spring:
  profiles: test

logging:
  level.ROOT: DEBUG
---
spring:
  profiles: online

logging:
  level.ROOT: INFO
  pattern.console:
  file: my-sample-server.log

# eureka online
eureka:
  client.serviceUrl.defaultZone: http://eureka-server-online:8761/eureka/

# DB Online
mySample.datasource.url: jdbc:mysql://sbmvt-mysql-online:3306/my_sample